---
meraki_api_key: "{{ lookup('env', 'MERAKI_DASHBOARD_API_KEY') | default(vault_meraki_api_key | default(''), true) }}"

meraki_org_name: ""
meraki_network_name: ""
meraki_network_names: []

meraki_discovery_api_retries: "{{ meraki_api_retries | default(3) }}"
meraki_discovery_api_retry_delay: "{{ meraki_api_retry_delay | default(2) }}"
